### ISSUE TITLE
Facing a problem 

### ISSUE THREAD

**Issue by diwalihabahi** [TheAxiome/discord_auto_prefix#2]
Hey, thank you soo much for this pkg and when i am changing  my guild prefix facing this error https://imgur.com/m0s9qks

this this is my code = const { aPrefix } = require('discord_auto_prefix')
const prefix = new aPrefix()

client.on('guildCreate', async guild => {
  prefix.defaultPrefix(guild, "!") //Sets the bots default prefix when it joins a new guild
})

client.on('guildDelete', async guild => {
  prefix.deletePrefix(guild) //Deletes the bots prefix data when leaving a guild
})

client.on('message', async message => {
  if (message.author.bot) return;
  if (message.channel.type === 'dm') return;

  const PREFIX = await prefix.fetchPrefix(message)

  if (!message.content.startsWith(PREFIX)) return; //If mesage isn't start with prefix then return
  const args = message.content.slice(PREFIX.length).split(" "); //Config Args(Arguements)
  const commandName = args.shift().toLowerCase();

  if (commandName === "setprefix") {
      if (!message.member.hasPermission("MANAGE_GUILD")) return;
      if (!args) return message.channel.send("No prefix was provided!")

      prefix.setPrefix(message, args)
  };

  if (message.author.bot) return;
  if (!message.guild) return;

    const command =
      client.commands.get(commandName) ||
      client.commands.find((cmd) => cmd.aliases && cmd.aliases.includes(commandName));

    if (!command) return;

    try {
      command.execute(client, message, args,);
    } catch (error) {
      console.error(error);
      message.reply("There was an error executing that command.").catch(console.error);
    }
}); 

and also if i want to use this ${PREFIX} we cant use it which it show that guild prefix like ex:- i have a code which give logs if finds channel and if channel is not there it will give  its return  message to that channel do ${PREFIX} + setup 
something like this so how can i do that

**Comment by TheAxiome** [comment]
Thank you for telling me this error, and for the feedback! I will figure something out right away! Sorry for the delay

**Comment by TheAxiome** [comment]
Update to the latest version, i added a command that will fetch any guilds prefix, i also fixed the embed color error, and I also answered one of your questions in the example code.

**Comment by TheAxiome** [comment]
This issue has been closed, updating to the new version will help with your error, version 1.4.4
